version: "3.8"

services:
  telefeed:
    build: .
    container_name: telefeed-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
